### ISSUE TITLE
Problem generating fake DateTime with MS SQL Server 

### ISSUE THREAD

**Issue by Starojitski** [laracasts/TestDummy#28]
When i specify in fixtures.yml a field like 
created_at: $date

i get following errors:
```
InvalidArgumentException: Data missing

#1  D:\.....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2547
#2  D:\.....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2479
#3  D:\.....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:407
#4  D:\.....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:249
#5  D:\.....\vendor\laracasts\testdummy\src\Laracasts\TestDummy\EloquentDatabaseProvider.php:31
#6  D:\.....\vendor\laracasts\testdummy\src\Laracasts\TestDummy\Builder.php:100
#7  D:\.....\vendor\laracasts\testdummy\src\Laracasts\TestDummy\Builder.php:149
#8  D:\.....\vendor\laracasts\testdummy\src\Laracasts\TestDummy\Builder.php:117
#9  D:\.....\vendor\laracasts\testdummy\src\Laracasts\TestDummy\Factory.php:61
#10 D:\.....\tests\_support\FunctionalHelper.php:12
```
What it comes down to is that fake data looks like ```'created_at' =>  string(19) "2014-04-02 18:19:52"```
But unlike DateFormat ```'Y-m-d H:i:s'``` from Database\Grammar.php, Illuminate\Database\Query\Grammars\SqlServerGrammar::getDateFormat() returns  ```'Y-m-d H:i:s.000'```
and 
```DateTime::createFromFormat('Y-m-d H:i:s.000', "2014-04-02 18:19:52")``` 
returns false;

I am not sure how to proceed. Not even sure who is in the wrong here: me? TestDummy? Carbon? Eloquent?

**Comment by JeffreyWay** [comment]
Fixed.
