### ISSUE TITLE
Problem of Duplicate entry

### ISSUE THREAD

**Issue by gold3bear** [laracasts/TestDummy#31]
I'm Learning the lesson  "21.Browsing Users With Pagination" of laracasts.
When I run UserRepositoryTest, I some times get a failure. it tells me: Duplicate entry username or email. 
```bash
1) UserRepositoryTest::it_paginates_all_users
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'quia' for key 'users_username_unique' (SQL: insert into `users` (`username`, `email`, `password`, `created_at`, `updated_at`) values (quia, asperiores@example.com, y$JZayLEON7qjipeooyaillOey6L1AHPidyXmsXRzbTyLpganKINEsK, 2013-11-19 20:17:46, 2014-05-04 21:07:12))

**Comment by cdarken** [comment]
@JeffreyWay any advice? I'm setting a custom id for the record and it seems like `create` is called multiple times in the same test. What am I doing wrong ?
