### ISSUE TITLE
Parenthesis bug on v1.3.4 + 1.3.5

### ISSUE THREAD

**Issue by graham192** [laracasts/TestDummy#51]
https://github.com/laracasts/TestDummy/commit/64b59a19bb0f7f772ab08acec07e38780a913a40

Illustrates a bug with parenthesis on v 1.3.5 + 1.3.4

**Comment by JeffreyWay** [comment]
Sorry I took so long to respond to this. If there's a PR for this, I'll merge it. 

Otherwise, definitely bump up to v2.
