### ISSUE TITLE
Factory::create assign empty string instead of null

### ISSUE THREAD

**Issue by LespiletteMaxime** [laracasts/TestDummy#61]
In a project I had a foreign key who should be null are a valid id, I notice TestDummy doesn't assign a valid null when creating but assign an empty string (""). 

I reproduce this issues on a simple exemple:

**Migration**

```php
Schema::create('posts', function(Blueprint $table)
{
	$table->increments('id');
	$table->string('title')->nullable();
	$table->timestamps();
});
```

**Model**

```php
class Post extends \Eloquent {
	protected $fillable = ['title'];
}
```

**UnitTest**

```php
public function testBasicExample()
{
     $post = TestDummy::create("Post",['title'=>null]);
     $this->assertNull($post->title);
}
```

**Result**

*1) ExampleTest::testBasicExample*
*Failed asserting that '' is null.*

**Comment by reinvanleirsberghe** [comment]
Having the same issue... Found a solution?

**Comment by JeffreyWay** [comment]
Can someone submit a PR for this?

**Comment by LespiletteMaxime** [comment]
I just try with Laravel 5 and last testdummy build and now it works fine.

**factories.php**

$factory('App\Post', [
    'title' => 'whatever'
]);

**ExampleTest.php**
$post = Factory::create("App\Post",[
				'title' => null
		]);
$this->assertNull($post->title);

**Result**
OK (1 test, 1 assertion)
