### ISSUE TITLE
Laracasts\TestDummy\TestDummyException: The path provided for the factories directory, tests/factories, does not exist.

### ISSUE THREAD

**Issue by woodytang** [laracasts/TestDummy#68]
this issue bugs me a lot, I use Phpstorm, why and any solutions?

**Comment by pavankumarkatakam** [comment]
Which version of laravel are you using?

**Comment by pavankumarkatakam** [comment]
With larevel version 5.0 tests is the root directory. so @JeffreyWay  given default path is "tests/factories" but in laravel 4 test folder is "app/tests/factories". Now to run it with laravel 4 you want to specify factories path explicitly see https://github.com/laracasts/TestDummy/#how-do-i-specify-a-different-factories-folder

**Comment by pavankumarkatakam** [comment]
Is it clear @woodytang
