### ISSUE TITLE
The {type} model was not found. 

### ISSUE THREAD

**Issue by hardikaecor** [laracasts/TestDummy#69]
I am trying to load the basic testdummy as follows
```php
<?php
                Factory::$factoriesPath = base_path() . '/tests/factories';
		$userAttributes = Factory::build('User');
		return $userAttributes;
```

and my tests/factories/users.php file is as follows:
```php
<?php
	$factory('User', [
		'first_name' => $faker->firstName,
		'last_name' => $faker->lastName,
		'email' => $faker->unique()->email,
		'password' => $faker->password,
		'gender' => $faker->randomElement(['Male', 'Female']),
		'activated' => $faker->boolean
	]);
```
but when i run, it gives me error
The User model was not found. 

does anyone knows what this is?

**Comment by gin93r** [comment]
I'm having the same issue when trying to use TestDummy for seeding. Basically the same setup as @hardikaecor . I've tried changing to `TestDummy::times(5)->create('App\Events');` but I get a TestDummyException `Could not locate a factory with the name: App\Events`. Without `App\` I get the same error as above.

**Comment by gin93r** [comment]
I was able to solve this by changing my factories.php file. I was using `$factory('Events'` instead of `$factory('App\Events'`.
