### ISSUE TITLE
Exception: The {name} model was  not found

### ISSUE THREAD

**Issue by Asvae** [laracasts/TestDummy#71]
I use artisan tinker as follows:
```
use Laracasts\TestDummy\Factory;
$factory = new Factory();
$factory->build('Comment');
```
As a result, I get TestDummyException with message 'The Comment model was
 not found.'
I checked $factory->factories() and it clearly says that factory with name: 'Comment' is included. Issue happened for any other factory I used.

**Comment by AlanRezende** [comment]
Try to use App\Comment

**Comment by AlanRezende** [comment]
```$factory->build('App\Comment');```
