### ISSUE TITLE
Overrides don't work with relations

### ISSUE THREAD

**Issue by bobbybouwmann** [laracasts/TestDummy#77]
So here is the issue. I have a user which has one role (role_id). When I create the user with TestDummy with overrides it gives an error while it creating the associated role!

This is my setup
```
// tests/factories/factories.php

$factory('App\User', [
    'name' => $faker->name,
    'email' => $faker->email,
    'password' => $faker->word,
    'role_id' => 'factory:Sebwite\Entry\Models\Role',
    'created_at' => $faker->date(),
    'updated_at' => $faker->date()
]);

$factory('Sebwite\Entry\Models\Role', [
    'name' => $faker->name,
    'display_name' => $faker->name,
    'description' => $faker->sentence(),
    'created_at' => $faker->date(),
    'updated_at' => $faker->date()
]);
```
> Note that the Role model is from a package, but I think it shouldn't matter since it's namespaced correctly.

And now the test part
```
// tests/_support/FunctionalHelper

 public function signIn()
{
        $email = 'foo@example.com';
        $password = 'password';
        $this->haveAnAccount(compact('email', 'password'));

        $I = $this->getModule('Laravel5');

        $I->amOnPage('/login');
        $I->fillField('email', $email);
        $I->fillField('password', $password);
        $I->click('Login');
}

public function haveAnAccount($overrides = [])
{
        return TestDummy::create('App\User', $overrides);
}
```` 

This is the error
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 table roles has no column named password (SQL: insert into "roles" ("name", "display_name", "description", "created_at", "updated_at", "email", "password") values (Vince Graham, Camila Mayert, Quis molestiae laboriosam id ea expedita., 2010-11-30 00:00:00, 1998-08-18 00:00:00, foo@example.com, password))
```
As you can see in the error it tries to insert the overrides for the User model in the Role model, while that shouldn't be happening! 

If you need anything else please let me know!

**Comment by blackbirddev** [comment]
So what I did was remove my vendor directory and installed everything again with `composer install`. It's working now so, I think it's fine!

**Comment by blackbirddev** [comment]
So after creating some more tests it started happening again, is this a real bug or am I doing something wrong?

**Comment by gfd6th** [comment]
Hi, I got the same issue with you.And reinstall the vendor by composer seems didn't work for me

**Comment by noleafclover614** [comment]
I also just started experiencing this behavior.

**Comment by bobbybouwmann** [comment]
`composer update` to TestDummy 2.1.2 fixed it for me!
