### ISSUE TITLE
Overriding attributes for relationships

### ISSUE THREAD

**Issue by adamwathan** [laracasts/TestDummy#82]
A few months back PR #52 was merged in which allowed overriding attributes for relationships.

Given these factories:

```php
$factory('Post', 'post', [
    'title' => $faker->word,
    'body' => $faker->sentence
]);
$factory('Comment', 'comment_with_post', [
    'post_id' => 'factory:post'
    'comment' => $faker->sentence
]);
```

...you could create a `Comment` like so and specify the `Post` body simultaneously:

```php
$comment = Factory::create('comment_with_post', [
    'comment' => 'First!',
    'body' => 'example'
]);
```

The flat nature of the attributes has led to some conflicts with other features like #65.

The issue is that this syntax provides no distinction between attributes that are meant for the `Comment` and attributes that are meant for the `Post`, so the entire attribute set is passed to both objects, meaning it tries to set the `comment` field on the `Post` and the `body` field on the `Comment`, even though those objects don't have those fields.

It creates more issues when two objects have a property of the same name, because now they will always have the same value and can't be set independently.

I'm opening this issue to start a discussion about an improved, explicit syntax that will allow this feature without the existing problems.

Two ideas I've had so far:

1. **Dot notation**

    Use dot notation to scope the related attributes.

    ```php
    $comment = Factory::create('comment_with_post', [
        'comment' => 'First!',
        'post.body' => 'example'
    ]);
    ```

    The string before the dot matches the *name* of the factory you are using for the relationship. So `Post` if you are using an unnamed factory, or `post` if you gave the factory an explicit name.
    
    The nice part about using a dot is that it's not a valid character in an object property, so it's very safe to treat any attributes containing dots as meant for relationships. It should be straightforward to make this work for nested relationships as well, like `post.author.name`.

    This is a decent simple solution but has limited flexibility if you ever have 2 relationships to the same factory, because there's no way to use separate attributes for each.

    Nevertheless, the value of handling that scenario might be lower than the value of using a simple syntax like this.

2. **Nested attributes**

    This one is trickier and I don't have a great syntax for it yet, but perhaps something like this.

    ```php
    $comment = Factory::create('comment_with_post', [
        'comment' => 'First!',
        'post_id' => [
            ':factory' => 'post',
            'body' => 'example'
        ]
    ]);
    ```

    This sort of approach is the most flexible but is tough to do nicely with arrays.

I think I like option 1 better despite the limited flexibility, but let's figure out if there's a better syntax.

**Comment by devinfd** [comment]
My personal preference is to have factories that are explicit and mirror the object attributes they are mocking for "documentations" sake but I totally get the idea of keeping them lean and "just valid enough." 

Last night I was thinking about this and what solution might satisfy both needs. I also come up with idea of a "dot notion". I think a dot notion would satisfy both needs and is also more clear when populating the relationship attributes. It also resolves the issue of `two objects having a property of the same name`

It would have to work with "short name" Factories `ie:admin_user.username` as well as namespace modals `i.e.: App\Users\User.username`.

**Comment by adamwathan** [comment]
Great, I'll cook up a PR for it.

The nice thing about this approach is it allows me to not define the ones I don't need but doesn't prevent you from doing it :)

**Comment by devinfd** [comment]
Sorry for being so unresponsive. I just got slammed with work.

I'm happy with this solution as well and happy to test it with my needs as well if need be. Thanks for taking the lead on this!
