### ISSUE TITLE
factories.php file makes PHPStorm Unhappy

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/TestDummy#89]
Anybody have a fix for this issue of PHPStorm thinking there is an error in the factories file due to the $factory variable being undefined (see screenshots below)

http://d.pr/i/SXIv

and here

http://d.pr/i/FWrX

**Comment by h-collector** [comment]
Put before first usage
```
/* @var $factory Closure */
```

**Comment by mikeerickson** [comment]
@h-collector Excellent, that was an easy fix!   Thanks mate :-)
