### ISSUE TITLE
Is unique() supported?

### ISSUE THREAD

**Issue by redgluten** [laracasts/TestDummy#90]
Hi, I’m not sure how to test if this a faker or TestDummy issue but I’m having trouble using the `unique()` [feature](https://github.com/fzaninotto/Faker#unique-and-optional-modifiers) of faker. My code looks like this:

```php
$factory('App\Product', [
    'sku' => $faker->unique()->ean13,
]);
```

It doesn’t work: the seeder runs fine but the EAN generated are all the same.

**Comment by TheShiftExchange** [comment]
Might be related to this? https://github.com/laracasts/TestDummy/issues/86

**Comment by gbrock** [comment]
Yep, use release 2.1 for the time being (from your composer.json):

```
    "laracasts/testdummy": "2.1",
```

**Comment by redgluten** [comment]
Tested on 2.1.2, same issue.

**Comment by TheShiftExchange** [comment]
@redgluten - you need to use `2.1.0` I believe

**Comment by redgluten** [comment]
Yeah sorry, figured that out after I wrote it. But still, the issue persists on 2.1:
```bash
vagrant@homestead:/var/www/marcapar$ composer show -i | grep dummy
laracasts/testdummy                   2.1     Easy test stubs
```

**Comment by JeffreyWay** [comment]
Recent commit should fix this.

**Comment by h-collector** [comment]
Hey, @JeffreyWay this issue isn't completely resolved.
That is if you use consequent calls to static create, then it can still fail
As an example, let's say we call it like this
```php
Laracasts\TestDummy\Factory::times(10)->create(Website::class, ['user_id'=>$id]);
Laracasts\TestDummy\Factory::times(20)->create(Website::class);
```
The chances are there will be uniques collision. 
```
[Illuminate\Database\QueryException]                                                                                                                                                           
  SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: websites.domain
```
The problem is that Faker instance after latest commits (testing on 2.3.1) is Builders private property and we always get new Builder instances, so used values for attributes aren't shared.
```php
    public static function create($name, array $attributes = [])
    {
        return (new static)->getBuilder()->create($name, $attributes);
    }
    public function getBuilder()
    {
        return new Builder($this->databaseProvider(), $this->factories());
    }
```
FakerAdapter should also use the same faker instance if we want to keep uniques.

This is still regression to version 2.1

**Comment by redgluten** [comment]
Unfortunately it doesn’t. :/

```bash
vagrant@homestead:/var/www/marcapar$ composer show -i | grep dummy
laracasts/testdummy                   2.3.1   Easy test stubs
```

![capture d ecran 2015-04-07 a 09 46 09](https://cloud.githubusercontent.com/assets/7190090/7018987/62c1d762-dd0b-11e4-9c89-15b49c744298.png)
