### ISSUE TITLE
Object of class Closure could not be converted to string

### ISSUE THREAD

**Issue by TheShiftExchange** [laracasts/TestDummy#91]
So I cant seem to do some basic PHP within the factory method?

This works:
```
$factory('Album', [
    'name' => $faker->name
]);
```

This fails with error ***Object of class Closure could not be converted to string***:

```
$factory('Album', [
    'name' => $faker->name.' add some text'
]);
```

**Comment by FourStacks** [comment]
I was just this minute running into the same issue. Everything was working correctly until I started adding some basic concatenation, much like @TheShiftExchange.

Best way around that though is to follow the suggestion in the docs and set up any custom strings via a closure e.g.

    $factory('App\Artist', function($faker) {
        $name = sprintf('Some Band Named %s', $faker->word);

        return [
            'name' => $name,
            'url' => $faker->url,
            // etc etc
        ];
    });

**Comment by JeffreyWay** [comment]
Yep - use a closure.
